INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `StringId`, `VerifiedBuild`) VALUES
(2000512, 0, 0, 0, 0, 0, 9129, 0, 0, 0, 'Jaedenar Legionnaire', 'Assauts de la Légion', NULL, 0, 80, 80, 0, 35, 1, 1.0e0, 1.0e0, 1.0e0, 0, 0, 2000, 0, 1.0e0, 1.0e0, 1, 0, 0, 0, 0, 7, 138936390, 0, 0, 0, 0, 0, 0, 0, '', 0, 1.0e0, 1.0e0, 1.0e0, 1.0e0, 1.0e0, 1.0e0, 0, 0, 1, 0, 0, 0, 'npc_jaedenar_legionnaire_netheril_guide', NULL, NULL);

INSERT INTO `creature_text` VALUES (2000512, 0, 0, 'Welcome, adventurer! I am the Jaedenar Legionnaire. Follow me, I will guide you to the Netheril camp.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - depart vaisseau');
INSERT INTO `creature_text` VALUES (2000512, 1, 0, 'It\'s not much further, keep following me.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - vaisseau 1');
INSERT INTO `creature_text` VALUES (2000512, 2, 0, 'This area is designed to gear you up with ilvl 245 gear.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - vaisseau 2');
INSERT INTO `creature_text` VALUES (2000512, 3, 0, 'It will help you prepare before facing Azeroth Universe\'s custom dungeons.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - vaisseau 3');
INSERT INTO `creature_text` VALUES (2000512, 4, 0, 'You will need to complete the Netheril achievement to access Azeroth Universe\'s custom dungeon.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - vaisseau 4');
INSERT INTO `creature_text` VALUES (2000512, 5, 0, 'Here we are. Stay close to me, I\'m teleporting you to Netheril Camp 1!', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - teleportation vers Netheril');
INSERT INTO `creature_text` VALUES (2000512, 6, 0, 'Here we are, we\'ve arrived at Netheril.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - arrivee camp');
INSERT INTO `creature_text` VALUES (2000512, 7, 0, 'Follow me, I\'ll show you around.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - intro visite');
INSERT INTO `creature_text` VALUES (2000512, 8, 0, 'Pick up your quests here, then we\'ll continue on our way.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - quetes 1');
INSERT INTO `creature_text` VALUES (2000512, 9, 0, 'This is where you\'ll find the creatures to defeat in order to earn gear vouchers, which you can then convert to equip yourself before Azeroth Universe\'s custom dungeons.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - zone creatures/bons d\'equipement');
INSERT INTO `creature_text` VALUES (2000512, 10, 0, 'You can also pick up gear around here.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - bons d\'equipement bis');
INSERT INTO `creature_text` VALUES (2000512, 11, 0, 'To access the first dungeon of the Lands of Fyra, S0 tier of Azeroth Universe, you\'ll need to earn the Netheril achievement.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - haut fait');
INSERT INTO `creature_text` VALUES (2000512, 12, 0, 'By defeating the creatures I showed you, you\'ll earn gear vouchers. Here, you can convert them into higher-tier gear vouchers.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - conversion des bons');
INSERT INTO `creature_text` VALUES (2000512, 13, 0, 'Here, you can buy your recipes.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - vente de recettes');
INSERT INTO `creature_text` VALUES (2000512, 14, 0, 'And here, on the Alliance side, is where you can also gear up using your vouchers.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - equipement Alliance');
INSERT INTO `creature_text` VALUES (2000512, 15, 0, 'Pick up your quests, then let\'s continue the tour.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - quetes 2');
INSERT INTO `creature_text` VALUES (2000512, 16, 0, 'By taking part in battlegrounds with the bots, you\'ll earn honor points, which can be exchanged for mounts or PvP gear.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - PvP/points d\'honneur');
INSERT INTO `creature_text` VALUES (2000512, 17, 0, 'New quests await you here, then we\'ll continue.', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - quetes 3');
INSERT INTO `creature_text` VALUES (2000512, 18, 0, 'Pick up your last quests here. Our tour of Netheril is coming to an end. Good luck on your adventure, adventurer. Farewell!', 12, 0, 100, 0, 0, 0, 0, 0, 'Guide Netheril - au revoir/fin');

INSERT INTO `creature_text_locale` VALUES (2000512, 0, 0, 'frFR', 'Bienvenue, aventurier ! Je suis le Légionnaire de Jaedenar. Suivez-moi, je vais vous guider jusqu\'au camp de Netheril.');
INSERT INTO `creature_text_locale` VALUES (2000512, 1, 0, 'frFR', 'Ce n\'est plus très loin, continuez de me suivre.');
INSERT INTO `creature_text_locale` VALUES (2000512, 2, 0, 'frFR', 'Cette zone est prévue pour vous équiper avec du stuff d\'ilvl 245.');
INSERT INTO `creature_text_locale` VALUES (2000512, 3, 0, 'frFR', 'Elle vous permettra de vous préparer avant d\'affronter les donjons personnalisés d\'Azeroth Universe.');
INSERT INTO `creature_text_locale` VALUES (2000512, 4, 0, 'frFR', 'Vous devrez accomplir le haut fait de Netheril pour accéder au donjon personnalisé d\'Azeroth Universe.');
INSERT INTO `creature_text_locale` VALUES (2000512, 5, 0, 'frFR', 'Nous y voici. Restez près de moi, je vous téléporte au Camp 1 de Netheril !');
INSERT INTO `creature_text_locale` VALUES (2000512, 6, 0, 'frFR', 'Nous voici arrivés à Netheril.');
INSERT INTO `creature_text_locale` VALUES (2000512, 7, 0, 'frFR', 'Suivez-moi, je vais vous faire visiter les lieux.');
INSERT INTO `creature_text_locale` VALUES (2000512, 8, 0, 'frFR', 'Prenez vos quêtes ici, puis nous continuons notre chemin.');
INSERT INTO `creature_text_locale` VALUES (2000512, 9, 0, 'frFR', 'C\'est ici que se trouvent les créatures à vaincre pour obtenir des bons d\'équipement, à convertir ensuite pour vous équiper avant les donjons personnalisés d\'Azeroth Universe.');
INSERT INTO `creature_text_locale` VALUES (2000512, 10, 0, 'frFR', 'Vous pouvez également récupérer vos équipements par ici.');
INSERT INTO `creature_text_locale` VALUES (2000512, 11, 0, 'frFR', 'Pour accéder au premier donjon des Terres de Fyra, palier S0 d\'Azeroth Universe, vous devrez obtenir le haut fait de Netheril.');
INSERT INTO `creature_text_locale` VALUES (2000512, 12, 0, 'frFR', 'En vainquant les créatures que je vous ai montrées, vous obtiendrez des bons d\'équipement. Ici, vous pourrez les convertir en bons d\'équipement supérieurs.');
INSERT INTO `creature_text_locale` VALUES (2000512, 13, 0, 'frFR', 'Ici, vous pourrez acheter vos recettes.');
INSERT INTO `creature_text_locale` VALUES (2000512, 14, 0, 'frFR', 'Et voici, côté Alliance, de quoi vous équiper également grâce à vos bons d\'équipement.');
INSERT INTO `creature_text_locale` VALUES (2000512, 15, 0, 'frFR', 'Prenez vos quêtes, puis continuons la visite.');
INSERT INTO `creature_text_locale` VALUES (2000512, 16, 0, 'frFR', 'En participant aux champs de bataille avec les bots, vous gagnerez des points d\'honneur, échangeables contre des montures ou de l\'équipement PvP.');
INSERT INTO `creature_text_locale` VALUES (2000512, 17, 0, 'frFR', 'De nouvelles quêtes vous attendent ici, puis nous continuons.');
INSERT INTO `creature_text_locale` VALUES (2000512, 18, 0, 'frFR', 'Récupérez vos dernières quêtes ici. Notre visite de Netheril touche à sa fin. Bonne chance dans votre aventure, aventurier. Au revoir !');
